config/routes.rb
Golfin::Application.routes.draw do
  
  resources :players do
  end
  
  resources :courses do
  end
      
  match '/signup',  to: 'players#new'
  
  post '/send_message', to: 'players#send_message'  

  get '/login',      :to => 'sessions#login'
  get '/auth/callback',   :to => 'sessions#create'
  get '/logout',     :to => 'sessions#destroy', via: :delete
  
  get '/home',       :to => 'static_pages#home'
  get '/about',      :to => 'static_pages#about'
     
  root              to: 'static_pages#home'
  
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if session[:atoken].nil?
    else
      @players = Player.all
      @courses = Course.all
    end
  end
  
  def about
  end
  
end

app/views/static_pages/_home_carousel.html.erb
<div class="" id="picture">
			
<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">

    <div class="active item" style="background:url('assets/image1.jpg') 10% 70% no-repeat; background-size:1000px;">
	<div class="feature">
		
		<h2>Expand Your Network</h2>
		<p>Connect talent with opportunity on and off the golf course</p>
		<p><i class="icon-trophy"></i><strong> Play on Golf [in]</strong></p>
		<%= link_to image_tag("LinkedIn_IN_Icon_25px.jpg") + " Login with LinkedIn", login_path, class: "btn btn-large btn-linkedin" %>
		
   	</div>
    </div>

    <div class="item" style="background:url('assets/image2.jpg') 80% 30% no-repeat; background-size:1000px;">
	<div class="feature">
		
		<h2>Find Connections</h2>
		<p>Want to learn more about your new connection? Play Golf!</p><br/><br/>
		<p><i class="icon-search"></i><strong> Find</strong></p>
		<%= link_to image_tag("LinkedIn_IN_Icon_25px.jpg") + " Login with LinkedIn", login_path, class: "btn btn-large btn-linkedin" %>
		
	</div>
    </div>

    <div class="item" style="background:url('assets/image3.jpg') 40% 30% no-repeat; background-size:1000px;">
	<div class="feature">
		
		<h2>Get Introduced</h2>
		<p>Connect with them on LinkedIn. You might be surprised at who you both know.</p>
		<p><i class="icon-inbox"></i><strong> Take the next step.</strong></p>
		<%= link_to image_tag("LinkedIn_IN_Icon_25px.jpg") + " Login with LinkedIn", login_path, class: "btn btn-large btn-linkedin" %>
	  
	</div>
    </div>
	
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

</div>

app/views/static_pages/home.html.erb
<% if session[:atoken].nil? %>
	
<div class="intro">
	
	<div class="center page-header">
	<br/>
	  <h2>It's not just a sport. It's a three martini lunch with golf carts.</h2>
	</div>
	
	<%= render 'home_carousel' %>
	
</div>

<% else %>

<div class="row">
	<div class="span7">	
	<div id='profiles'>
		<div class='profile show home'>
			
			<div class="page-header"><h1 style="text-align: left;">Players League</h1></div>
				
			<% for player in @players%>
			<div class="top_half">
				<%= link_to image_tag(player.picture_url.nil? ? 'empty_avatar.png' : player.picture_url, :class => 'profile_picture', :size => '50x50'), player_path(player.id)%>
				<p><%= player.first_name%> <%= player.last_name%></p>
				<p id="company"><%= player.company %></p>
			</div>

			<div class="label center" id="handicap">
				<h2>Handicap</h2>
				<p><%= player.handicap %></p>
			</div>
			<% end %>
		</div>
	</div>	
	</div>
	
	<div class="span5">	
		<div class="page-header"><h1 style="text-align: left;">Club House</h1></div>
		
		<% for course in @courses %>
			<% n = [1,2,3,4].sample %>
			
			<div class="courses">
			<h5><%= course.name %></h5>
			<%= link_to image_tag("course#{n}.jpg", :class => 'course_picture', :size => '90x80'), course.link %>
			
			<div class="course_stats">
				<p><%= course.holes %> Holes</p>
				<p><%= pluralize(Player.where(:home_course => course.id).count, 'Club Member')%></p>
			</div>			
			
			</div>
		<% end %>
		
	</div>
	
</div>
	
<% end %>