config/routes.rb
Golfin::Application.routes.draw do
  
  resources :players do
  end
  
  resources :courses do
  end
      
  match '/signup',  to: 'players#new'
  
  post '/send_message', to: 'players#send_message'  

  get '/login',      :to => 'sessions#login'
  get '/auth/callback',   :to => 'sessions#create'
  get '/logout',     :to => 'sessions#destroy', via: :delete
  
  get '/home',       :to => 'static_pages#home'
  get '/about',      :to => 'static_pages#about'
     
  root              to: 'static_pages#home'
  
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About ",   about_path, :rel=>'tooltip', :id=>'tooltip', :title=>'Learn About Our Team!' %></li>
      <li><%= mail_to "admin@decisionmkr.com", "Contact", :subject => 'Feedback', :rel=>'tooltip', :id=>'tooltip', :title=>'Send Us Feedback!', :encode => 'javascript' %></li>
	  <li><%= link_to "News", '#', :rel=>'tooltip', :id=>'tooltip', :title=>'Coming Soon - Visit Our Blog!'%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to  ("Golf "+image_tag('LinkedIn_IN_Icon_25px.jpg', :size => '20x1', :style => "border-radius: 3px; position:relative; top:-2px; left:-4px;")).html_safe, root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
		
		  <% if session[:atoken].nil? %>
		  <% else %>
          <li><%= link_to ('<i class="icon-home icon-white"></i> Home').html_safe,    root_path %></li>

          <li><%= link_to ('<i class="icon-search icon-white"></i> Search').html_safe, players_path %></li>
          <% end %>

		  <% if session[:atoken].nil? %>
		  <li><%= link_to "Log in", login_path %></li>
		  <% else %>
		
			<% if current_player.nil? %>
				<li id="fat-menu" class="dropdown">
	              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-wrench icon-white"></i>Settings <b class="caret"></b></a>
	                <ul class="dropdown-menu">
					<li><%= link_to "Create Profile", signup_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Sign out", logout_path %></li>
					
			<% else %>
		  
		  <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> My Profile <b class="caret"></b></a>
                <ul class="dropdown-menu">
               <li><%= link_to "View Profile", current_player %></li>
			   <li><%= link_to "Update Profile", edit_player_path(current_player) %></li>
               <li class="divider"></li>
               <li><%= link_to "Sign out", logout_path %></li>

			<% end %>
			<% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_search.html.erb
<% if session[:atoken].nil? %>
<% else %>
<header class="navbar navbar-fixed-top-index">
  <div class="navbar-inner navbar-index">
    <div class="container">
       <nav>

		<ul class="nav" style="margin-left:-10px;">
          <li><%= link_to "Find Connected Reviews", {:controller => 'users', :action => 'index', :search => 'query_reviews'} %></li>
          <li><%= link_to "Find Your Connections", {:controller => 'users', :action => 'index', :search => 'query_connections'} %></li>
        </ul>
		
		<%= form_tag "users", :method => 'get', :class => 'navbar-search' do %>
		  <%= text_field_tag "search", nil, :class => "search-query", :placeholder => 'Search for a person or company', :autocomplete => 'off', :data => { :provide => 'typeahead', :source => @dropdown_companies} %>
		<% end %>

	   </nav>
	</div>
  </div>
</header>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
 <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
 <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>
	
<%= render 'layouts/header' %>
<%#= render 'layouts/search' %>	
<div class="container" style="padding-top: 40px;">	

	<% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
	
	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>

</div>

</body>
</html>